apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_PASSWORD: AgC+6qAisEANoBgP/QTQAUo4xGTdZfngPmPp8ms8Zu6p5eB8J1kxBT00NciE7qLlaYFD4+kPTl9XLZvUnzD6H6DtDC6/YUugXgzllKI193akx8aFGvMUy/sEooT6UFv5DMdtIwCAyQFa7fLbqb1MjqXW6z85gayLJG5ioEyjplUm9DsDOq43dLuOGv2VPmHpPNTwjBvcnnCNzZ74nc4M4tHufW6yipe3akv+FQa5MWVAQB+FTLKORTUU4j2rkyD4mg9y7RRwgmf12js+beT+FhMkwGbWK4io7QpNW8vMPMqDDH9jiFXJ/rCIC3mmz9vcihnOLcCjusm5VNoVhjfZgIepl3oDRI5W7XZ9+gkmz7VBMT5DnzkjbmdwnVi77Wi/2qe8oLF/N5xoAOa1MJDmIas0s5VJW1kHjcqLMSfvAWlrfItIeVZ+bHR+tKRuCvZkJQvAmlSaJ0SIUPnMbeowlzro5ymxqVAJKlKXYDPEsy7tUCrWiG7q0FvPV35C+EBCsf7SjkJk7XB13mzKMB1C/QHReVmAOZ510RBDW73li2sggA7hXw1jm2F8+qCoc3ux+lUdgunf9uBGXQDI3Mzd+b3wVMT/41B8g2i1nvHITCCHOzD6vWY5ybfX9CP3DSgUwJIn64QL/ZK/KHRqaxY7mzKSAzjHWjeY3JS7nUxFwAeA/v4Rw7frOZnVo948NVH27IUivfTmN9YoFA==
    ARTIFACTORY_URL: AgBBCMeZD07B9LwXnYbcNhLit7CNfXxBJVPqb/h5TtIGQ3cOQUJ4OldmNdqQosPaR3AKfIwJk2i/MIrGUSRyutFbCuEkU49tgmig3C2JwI8DCgrdnXrdE/OTsnVs0Ax8cVeIJlkHhdKIIHHmlOQQTbIsnU4ugVqowonkAPKh1nXDQq5kwhDrdz8EcDxGyiqWpDDasE7XdWsr6KpIk+LaVuKIpVdMDJEJgpinz51DoCLn/U4LXLH21Botf/UkThO9UA7BnEsL7oGhQGpNkbQluF3VnMnIEnBPreBReyUW0CfkjcsRjU3EVqdlzwGIFNAE7uRwk5z43w1oMicEWtwbz00kq0w3EqHQ/YSpBuXnEXL3+UHt+1fMZsD8Q3ZC3uw74BclbR0etC/4EMcVHV/rAV/kVDHqPN3W8yphx4ejUW7JWIBdgtDdhVSo35u9t2PlNSg1/4334NuxCSvX2/vY6oemkXm8x+U0BdDKbCbE4Fa2FU99x31pg4L6TNeIyT+99INunz8+HfBWVMaf2NL6p4TejRy9S0COPd6+bsfbVNUx5cKadH7Qd1ozHsnDD0F9E4CAKKnlZEtA8CFdHcZQLLXo4/PM5PZRUrUZR6rbJWn2VzrioeFgoWImS0XdUA2STJnOzIleMCTT5zrMTasR4gsCuY9MSZbTV1ZX7K88Ae2WTIsOJLqMm0VVIxXoCwzjVEa6zkNn71C/3fg7453jbfU28QILDY4gcyKKq7WX8XdeuRiml2JIisA1LA==
    ARTIFACTORY_USER: AgDBQvDOCc3UtmWcKXfwtdhpsMccWgYTGozsov/YFLEnj/6VpFCAHtKtbWwrZbIFUbsuOqev4UwE2mzN8SyV5mRPscXnVSY4vRZoDZXfmvsZuCWg7xORbhwo0FHrCSoMz2MfruAze9rzLFlRXxlmqwbduH4J10Gxxo8xErCP8332BgaV5b8260zAiDmpLkzrpZWfe8Fgz8OaukwgViKNx7/lQdmsaET0SoKTRLa/jlKEBJ2m/LiSNQ+7gpvta+QkNkCP8t33LXa7Io/S5zx6P1wy/hQCx10D8CLPGtWioSFOtIYmGHf/VM4+5ILY5WxECEnxgCgCCvIvVwhhYYr0RfRECFFF75LvptqTmRf1+x9eGN6fqkR5gaUjcswTnW3PJAWmH2OS35GW11VOU0x8lkfysM3qIgsiplWdlNG8zd849ziUqKWiW2K/Jothu+iI/sl2uYYLpPPV6b8aBWjCu1mNBRzTaHfIUuNiVLHbD5MYzqG3HC6/gYy0Og2XCEKE10AadLKKa5/bLv3IgzUUzdkAtlYwA0H7Y1uAww5n1FAjtTrvYBy5ZNMrMvLBfV/I3FsegG8H/99IcjRKJqcrROymEGvj5EGkKeacZUnEc7OT0IJuAZyTppWEG+Kb8cM7qi9elhhEJjjUtPkaA9G/uyaJprKPv258cmOoXjds+yq8lEed6wPlU9yrR2j8ftSFeTxjXdhNYA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:ownerReferences:
              .: {}
              k:{"uid":"46f46987-b366-417e-983f-bcb0feb7d854"}:
                .: {}
                f:apiVersion: {}
                f:controller: {}
                f:kind: {}
                f:name: {}
                f:uid: {}
          f:type: {}
        manager: controller
        operation: Update
        time: "2022-03-03T17:17:06Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

