apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: main
  host: github.com
  org: cloud-native-toolkit-gitops
  owner: cloud-native-toolkit-gitops
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/cloud-native-toolkit-gitops/multi-tenancy-gitops-apps.git
