apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: main
  host: gitea-tools.instana-mq-6qwkjtsh-b9aa1303e037748136e24e1f282ebee9-0000.us-south.containers.appdomain.cloud
  org: gitops-org
  owner: gitops-org
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/cloud-native-toolkit-gitops/multi-tenancy-gitops-apps.git
