apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgDZslmItR3mlCPzrBEHKT9kfl3InMI1lXjUbweUv9TLlJHicWAbnol2i2xy8cNkjQzrOzlySc5nFwRjsz+T4Tz9RwSNrrH/4TMMvjWy8TvdFIoYEaSptQ9KyfFUFtViggs8cV2fTt36DqiJRnxAwUMpZXYQ3kspjrbUHGpPMNCGvR/fRl1RzHc8Lc/jFYq6GmcNRA8Ek9PU77TuHCgXA8USYvegQSp5dsk7wFypYk+/ZNbfdTDyka1EtqFz5noxuJ26UZpJdM36O5B7bs3Na742xh3MA+woIvf+dSjxdlwIrZtPy5i8nNyfgrPgH3Eh9kfv+OT/WUv1bGwMK9ChMeO/YQtLvkepu/0vkqe8Y/9Bw0iX/xEhA6aLYz00cCYyhOi1A6+IhkQkqUL2qWCtcfH0nJV6pPyFVQBoYKe2G+DLEBBS5X3lfMayKFBcxxiWbjDu3HSg4aekeY2XzXXqjVKnpWaT/HqDgavcMH9aPmX+ito20FUq3onylatlXj1aZ6HjPZSidDjKY7fJ92hv6VQMKxDaR1P2bWiLyQpfeakDSQNFjUtufWIb2pirA8kJjQPgxX690v90lCnPkJ6gCc5lqyz4wUDMiyYhFmwyCCw2d/W/tfDFEyUxP2SswvqOmZGqkcGtXiCY2BoO042NxZF9GmAFYT26qUPBxrFBgkiX399xe1MAlY9mm6G1Ei0kFUHghtZMIrOM
    username: AgCa3jSLixJZmGuNy2eAjNLyH7xmZS8VKCIWGJQARuHxN8CqDFhiBb2GwCUb9WxBCDdWUN+KgbjxV5XO1SjTsYNTDgF/JDyf5rRfEpQTpSxZe2KU/beL/VUBRp90D0Xa2/cjNqenh1NUSE/jJkmSfznn05hflxlEh86r8AgKWUby7OuNecT9cdfBPwHJW2kw9ioMC8dStUu0jmptusHStrMhT5RRfXryweGki/6+63pYNe2PDudqwmWOH8PUVMgYGUHT2G1ZBHZGEkrcwMSlcFmonIAMGAiNpjmZtH56GJp8b9hdSvmytU1loZxh9DJTMMutdei0GAqQjGvcNUkkm9s0mr69AGcNmZ8zGMaxmFMlLgzR6p/lBlfN6PnJpBRK7VyYtyWEdtymDmdD+Vkpjq/fa5CbSzDN13ZkGAPhweK8QT6qlzcFPY+l0Ho7ZmIh8Qbw1l9i7c+62J6NWp9n3M81uIrL82D5RgSOS+0ZtfjJxdr7bqfr7ZA33Iw4o1PXagg5E811En9zz3Q7E0XWe8PpSA12Q+aGeFGEcQwO3Gm0ldJeUpPdrgXQHUv3xVKgzZTLh8QmU6xSJ/JcQhH4VVMGtcnq3DXwItFt5T1sRhu3Su42+9H78A8InkO/Y/TZzfJ1/GnAWPSIKpHQH7uT3QFt+9ygy1ZbYKVUdFMrUmaviU7AbjgbJRMXEu9sNqcWd512g3dnzo4q
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

